# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ccista_conv <- function(S, X0_, LambdaMat, lambda2, epstol, maxitr, steptype) {
    .Call('_gconcord_ccista_conv', PACKAGE = 'gconcord', S, X0_, LambdaMat, lambda2, epstol, maxitr, steptype)
}

ccfista_conv <- function(S, X0_, LambdaMat, lambda2, epstol, maxitr, steptype) {
    .Call('_gconcord_ccfista_conv', PACKAGE = 'gconcord', S, X0_, LambdaMat, lambda2, epstol, maxitr, steptype)
}

ccorig_conv <- function(S, X0_, LambdaMat, lambda2, epstol, maxitr) {
    .Call('_gconcord_ccorig_conv', PACKAGE = 'gconcord', S, X0_, LambdaMat, lambda2, epstol, maxitr)
}

